export const userTypes = {
  USER_FETCH_DATA_START: 'USER_FETCH_DATA_START',
  USER_FETCH_DATA_FAILED: 'USER_FETCH_DATA_FAILED',
  USER_FETCH_DATA_SUCCESS: 'USER_FTECH_DATA_SUCCESS',
  USER_FETCH_REGALOS_START: 'USER_FETCH_REGALOS_START',
  USER_FETCH_REGALOS_SUCCESS: 'USER_FETCH_REGALOS_SUCCESS',
  USER_FETCH_REGALOS_FAILED: 'USER_FETCH_REGALOS_FAILED',
  USER_REFRESH_TOKEN: 'USER_REFRESH_TOKEN',
};
