export const authTypes = {
  USER_SIGNIN: 'USER_SIGNIN',
  USER_SIGNIN_START: 'USER_SIGNIN_START',
  USER_SIGNIN_SUCCESS: 'USER_SIGNING_SUCCESS',
  USER_SIGNING_FAILED: 'USER_SIGNIN_FAILED',
  USER_SIGNUP_START: 'USER_SIGNUP_START',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',
  USER_LOGGED: 'USER_LOGGED',
  USER_LOGOUT_START: 'USER_LOGOUT_START',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCES',
  USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED',
};
